CREATE TABLE ANIMAL (
	ID_ANIMAL SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE VACINA (
	ID_VACINA SERIAL PRIMARY KEY,	
	ID_ANIMAL INT NOT NULL,
	DT_VACINA TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	PESO NUMERIC(15, 2) NOT NULL,
	DOSAGEM NUMERIC(15, 2) NOT NULL,
	APLICADOR VARCHAR(100) NOT NULL,
	DESC_MEDICAMENTO VARCHAR(100) NOT NULL,
	FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL)
);

INSERT INTO ANIMAL (DESCRICAO) 
	VALUES ('ANIMAL 1'),
	('ANIMAL 2'),
	('ANIMAL 3'),
	('ANIMAL 4');